# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: haz-algos
version: '0.0.0'
github: "villagerz/haz-algos"
license: MIT
author: "Anand Mishra"
maintainer: "Anand Mishra"
synopsis: A package to try out functional programming data structires and algorithms
# description: haz-algos is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

dependencies:
- base-unicode-symbols
  
default-extensions:
- UnicodeSyntax
  
ghc-options: -Wall

library:
  dependencies:
  - base
  - array
  source-dirs: library

executables:
  haz-algos:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - haz-algos
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  haz-algos-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - haz-algos
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  haz-algos-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - haz-algos
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
